name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build SimpleCountDownTimer app release bundle (AAB)
      id: buildRelease
      run: ./gradlew bundleRelease

    - name: Sign SimpleCountDownTimer app bundle
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{secrets.SIGNING_KEY}}
        alias: ${{secrets.ALIAS}}
        keyStorePassword: ${{secrets.KEY_STORE_PASSWORD}}
        keyPassword: ${{secrets.KEY_PASSWORD}}

#    - name: Upload SimpleCountDownTimer app bundle
#      id: uploadArtifact
#      uses: actions/upload-artifact@v1
#      with:
#        name: SimpleCountDownTimer
#        path: app/build/outputs/bundle/release/app-release.aab

    - name: Write service_account.json (needed for Google Play Publishing) from secrets to a local file
      id: CreateServiceAccountJson
      run: echo '${{secrets.SERVICE_ACCOUNT_JSON}}' > service_account.json

    - name: Deploy SimpleCountDownTimer upload to Play Console
      id: deploy
      uses: ikd9684/upload-google-play@v1
      with: 
        serviceAccountJson: service_account.json
        packageName: jp.co.excite_software.s_ikeda.simplecountdowntimer
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal
